
#生产环境配置
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://106.12.21.25:3306/db_pro_wms?userSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: ENC(keVXLdMP2hvdjcJfzTVPpQ==)
    password: ENC(7uPqC3ZqMZ0XI3pavqezFxzsCIxWz4IY)
    dbcp2:
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 18800
    #连接数据库断开
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1

server:
  port: 8088




